memory_limit = 512M

max_execution_time = 300

date.timezone = Asia/Jakarta

post_max_size = 64M

upload_max_filesize = 64M

session.save_handler = files
session.save_path = "/tmp/php-sessions"
session.gc_maxlifetime = 1440
